### PR TITLE
Database script some endpoints update

### PR DESCRIPTION
**Pull request by 0ceanCat**
created new tables: cinema, seat and room.
changed some primary key to superkey.
updated api.txt
changed some urls of filmController

### CODE REVIEW

**Review by davidgmorais — APPROVED** [review]
Good job

**Review by marianabladeiro — CHANGES_REQUESTED** [review]
Looks good, don’t forget to add an header image field on the Film!

**Comment by 0ceanCat** [comment]
> Looks good, don’t forget to add an header image field on the Film!

hmmm, but we have column "picture"

**Review by marianabladeiro — APPROVED** [review]
Looks good!

**Pull request merged**
